-- MySQL Script generated by MySQL Workbench
-- Wed Dec  6 13:17:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- stampee -- JLl2AH6eOoD6Ru7pOjhO

-- -----------------------------------------------------
-- Table `priviege`
-- -----------------------------------------------------
CREATE TABLE `privilege` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `privilege` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`));

INSERT INTO `privilege` (`id`, `privilege`) VALUES
(1, 'admin'),
(2, 'employee'),
(3, 'membre');

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE `user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NULL,
  `email` VARCHAR(50) NOT NULL UNIQUE,
  `phone` VARCHAR(50) DEFAULT NULL,
  `address` VARCHAR(100) DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `tempPassword` varchar(255) DEFAULT NULL,
  `privilege_id` INT NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`privilege_id`)
    REFERENCES  `privilege` (`id`)
);

INSERT INTO `user` (`id`, `username`, `email`, `phone`, `address`, `password`, `tempPassword`, `privilege_id`) VALUES
(1, 'Tim', 'tim@gmail.com', '000000', '000000', '$2y$10$PEpbCnd1roxLR.TsPUejA.II9HNEEitWooDTgkg60c/UmLUCVmJoW', NULL, 3),
(2, 'Judy', 'judy@gmail.com', '000000', '000000', '$2y$10$52XSI8XiyRtoYP8bIIPhBeimw36RJyYCLkebZVp7PydtuUBTpRO96', NULL, 3),
(3, 'Mike', 'mike@gmail.com', '000000', '000000', '$2y$10$OJoR6zRsoPz1j2Tl4JO0huUDk4i5YfLjvCxcgdeWHSlyQmcx8XPbK', NULL, 3),
(4, 'Nancy', 'nancy@gmail.com', '000000', '000000', '$2y$10$qZ5hS1yQouIXtiE1BglzM.e.QGkBbnpTGaaxzJHf9SwSCSFLohaXy', NULL, 3),
(5, 'Sam', 'sam@gmail.com', '000000', '000000', '$2y$10$IdYLH71jU5ulcZhKUQVUdeEOg38IjSRVvd/owX1PrGn47tH4bnIZ2', NULL, 3),
(6, 'Jhon', 'jhon@gmail.com', '000000', '000000', '$2y$10$ZeLcnY.1MpHR0RKVQLBX2.Ea8Yv9nTwwxKGJiwlJbtjjJjq4STC0W', NULL, 3),
(7, 'Admin', 'admin@gmail.com', NULL, NULL, '$2y$10$pOb7QGmuFp0Y3vhPydy3mOHJcNaRE4lKJ8kjSJsyEBFKN5ie/jDv.', NULL, 1),
(8, 'Employee', 'employee@gmail.com', NULL, NULL, '$2y$10$lzhGnucLq/mSIaG.0BCdkuvAEKNGt3HmaUxwm3JGx0Sd6wKMuJ9xy', NULL, 2),
(9, 'Membre', 'membre@gmail.com', '000000', '000000', '$2y$10$vmzuuaetFbtTi3tkznow3.VqploZF5XHK8RdvwHZQxDDH6eSfqzDq', NULL, 3);
-- 000000 --

-- -----------------------------------------------------
-- Table `categorie`
-- -----------------------------------------------------
CREATE TABLE `categorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categorie` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO `categorie` (`id`, `categorie`) VALUES
(1, 'Art'), 
(2, 'Science'), 
(3, 'Sport'),
(4, 'Personnage'), 
(5, 'Animal'),
(6, 'Plante');

-- -----------------------------------------------------
-- Table `pays`
-- -----------------------------------------------------
CREATE TABLE `pays` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pays` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO `pays` (`id`, `pays`) VALUES
(1, "Canada"),
(2, "États-Unis d'Amérique"),
(3, "Royaume-Uni"),
(4, "France"),
(5, "Japon"),
(6, "Chine");

-- -----------------------------------------------------
-- Table `enchere`
-- -----------------------------------------------------
CREATE TABLE `enchere` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prix_depart` DOUBLE DEFAULT NULL,
  `date_debut` DATETIME NOT NULL,
  `date_fin` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`user_id`)
    REFERENCES  `user` (`id`)
);

INSERT INTO `enchere` (`prix_depart`, `date_debut`, `date_fin`, `user_id`) VALUES
(null, '2023-12-04', '2023-12-31', 1),
(null, '2023-12-04', '2023-12-31', 2),
(null, '2023-12-04', '2023-12-31', 3),
('1', '2023-12-04', '2023-12-31', 4),
('1', '2023-12-04', '2023-12-31', 5),
('1', '2023-12-04', '2023-12-31', 6);

-- -----------------------------------------------------
-- Table `timbre`
-- -----------------------------------------------------
CREATE TABLE `timbre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(200) NOT NULL,
  `description` VARCHAR(2000) NULL,
  `annee` VARCHAR(4) NULL,
  `enchere_id` INT NOT NULL,
  `categorie_id` INT NOT NULL,
  `pays_id` INT NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`enchere_id`)
    REFERENCES  `enchere` (`id`),
    FOREIGN KEY (`categorie_id`)
    REFERENCES  `categorie` (`id`),
    FOREIGN KEY (`pays_id`)
    REFERENCES  `pays` (`id`)
);

INSERT INTO `timbre`(`nom`, `description`, `annee`, `enchere_id`, `categorie_id`, `pays_id`) VALUES
("SG197 VFU Wmk Inverted, part oval datestamp", "Le Penny Black est le premier timbre postal de l'histoire. Il a été émis le 1er mai 1840 au Royaume-Uni de Grande-Bretagne et d'Irlande à l'initiative de Rowland Hill, pour un usage officiel à partir du 6 mai, dans le cadre de la réforme du système postal britannique destinée à faire désormais payer l'expéditeur plutôt que le destinataire.", "1887" , 1, 1, 1),
("SG94 Pl.14 Mint Unmounted o.g. example (RK)", "Le Penny Black est le premier timbre postal de l'histoire. Il a été émis le 1er mai 1840 au Royaume-Uni de Grande-Bretagne et d'Irlande à l'initiative de Rowland Hill, pour un usage officiel à partir du 6 mai, dans le cadre de la réforme du système postal britannique destinée à faire désormais payer l'expéditeur plutôt que le destinataire.", "1873", 2, 2, 2),
("SG197 VFU Wmk Inverted, part oval datestamp", "Le Penny Black est le premier timbre postal de l'histoire. Il a été émis le 1er mai 1840 au Royaume-Uni de Grande-Bretagne et d'Irlande à l'initiative de Rowland Hill, pour un usage officiel à partir du 6 mai, dans le cadre de la réforme du système postal britannique destinée à faire désormais payer l'expéditeur plutôt que le destinataire.", "1887", 3, 3, 3),
("SGO67 Official(Govt. Parcels) unused o.g. example", "Le Penny Black est le premier timbre postal de l'histoire. Il a été émis le 1er mai 1840 au Royaume-Uni de Grande-Bretagne et d'Irlande à l'initiative de Rowland Hill, pour un usage officiel à partir du 6 mai, dans le cadre de la réforme du système postal britannique destinée à faire désormais payer l'expéditeur plutôt que le destinataire.", "1888", 4, 4, 4),
("SG197 VFU Wmk Inverted, part oval datestamp", "Le Penny Black est le premier timbre postal de l'histoire. Il a été émis le 1er mai 1840 au Royaume-Uni de Grande-Bretagne et d'Irlande à l'initiative de Rowland Hill, pour un usage officiel à partir du 6 mai, dans le cadre de la réforme du système postal britannique destinée à faire désormais payer l'expéditeur plutôt que le destinataire.", "1887" , 5, 5, 5),
("SG94 Unmounted o.g. example (RK)", "Le Penny Black est le premier timbre postal de l'histoire. Il a été émis le 1er mai 1840 au Royaume-Uni de Grande-Bretagne et d'Irlande à l'initiative de Rowland Hill, pour un usage officiel à partir du 6 mai, dans le cadre de la réforme du système postal britannique destinée à faire désormais payer l'expéditeur plutôt que le destinataire.", "1873", 6, 6, 6);

-- -----------------------------------------------------
-- Table `image`
-- -----------------------------------------------------
CREATE TABLE `image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(50) NOT NULL,
  `timbre_id` INT NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`timbre_id`)
    REFERENCES  `timbre` (`id`)
);

INSERT INTO `image` (`filename`, `timbre_id` ) VALUES
("1.jpg",1),
("2.jpg",2),
("3.jpg",3),
("4.jpg",4),
("5.jpg",5),
("6.jpg",6),
("11.jpg",1),
("12.jpg",2),
("13.jpg",3),
("14.jpg",4),
("15.jpg",5),
("16.jpg",6),
("21.jpg",1),
("22.jpg",2),
("23.jpg",3),
("24.jpg",4),
("25.jpg",5),
("26.jpg",6);

-- -----------------------------------------------------
-- Table `mise` 
-- -----------------------------------------------------
CREATE TABLE `mise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `enchere_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `prix` DOUBLE NOT NUL CHECK (prix > 0),
  PRIMARY KEY (`id`),
    FOREIGN KEY (`enchere_id`)
    REFERENCES  `enchere` (`id`),
    FOREIGN KEY (`user_id`)
    REFERENCES  `user` (`id`)
);

INSERT INTO `mise` (`enchere_id`, `user_id`, `prix`) VALUES
(1, 1, 100),
(1, 2, 120),
(1, 3, 130),
(2, 1, 210),
(2, 2, 220),
(2, 3, 230),
(3, 3, 300),
(4, 4, 400),
(5, 5, 500);

-- -----------------------------------------------------
-- Table  `favori` 
-- -----------------------------------------------------
CREATE TABLE `favori` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `enchere_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`enchere_id`)
    REFERENCES  `enchere` (`id`),
    FOREIGN KEY (`user_id`)
    REFERENCES  `user` (`id`)
);

INSERT INTO `favori` (`enchere_id`, `user_id`) VALUES
(1,1),(1,2),(1,3),(1,4),(1,5),(1,6),
(2,1),(2,2),(2,3),(2,4),(2,5),(2,6);

-- -----------------------------------------------------
-- Table  `contact` 
-- -----------------------------------------------------

CREATE TABLE `contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50),
  `email` VARCHAR(50) NOT NULL,
  `message` TEXT (2000),  
  PRIMARY KEY (`id`)
);

INSERT INTO `contact` (`nom`, `email`, `message`) VALUES
('Peter', 'peter@gmail.com', 'Bon !'),
('Sharon', 'sharon@gmail.com', 'Tres bon !'),
('Richard', 'richard@gmail.com', 'Pas mal !'),
('Sharon', 'sharon@gmail.com', 'Hello !'),
('Richard', 'richard@gmail.com', 'Allo !');

-- -----------------------------------------------------
-- Table  `contact` 
-- enchere_id UNIQUE防止多次推荐
-- -----------------------------------------------------

CREATE TABLE `recommande` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `enchere_id` INT UNIQUE,  
  PRIMARY KEY (`id`)
);

INSERT INTO `recommande` (`enchere_id`) VALUES
(73),
(74),
(75),
(77),
(78),
(79),
(80),
(81);
